{{ if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ogmios.fullname" . }}
  labels:
    {{- include "ogmios.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.releaseName }}
spec:
  endpoints:
    - path: /metrics
      port: {{ .Values.service.port | quote }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "ogmios.labels" . | nindent 4 }}
{{ end }}