---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kupo.fullname" . }}
data:
  init.sh: |
    git clone https://github.com/easy1staking-com/cardano-node-configuration.git /tmp/cardano-node-configuration
    cp -a /tmp/cardano-node-configuration/{{ .Values.network }}/*.json /config
