{{ if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "midnight-node.fullname" . }}
  labels:
    {{- include "midnight-node.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.releaseName }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "midnight-node.selectorLabels" . | nindent 6 }}
{{ end }}