---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "midnight-node.fullname" . }}-internal
  labels:
    {{- include "midnight-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9944
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: 30333
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "midnight-node.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "midnight-node.fullname" . }}
  labels:
    {{- include "midnight-node.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 30333
      targetPort: p2p
      protocol: TCP
      name: p2p
      nodePort: 30333
  selector:
    {{- include "midnight-node.selectorLabels" . | nindent 4 }}
