apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "iagon.fullname" . }}
  labels:
    {{- include "iagon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "iagon.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "iagon.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "iagon.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.maintenance | default false }}
          command: [ "sh", "-c", "sleep infinity" ]
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ include "iagon.fullname" . }}-volume
              mountPath: {{ .Values.volume.mountPath }}
            - name: home
              mountPath: /root
      dnsPolicy: Default
      volumes:
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: home
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
    - metadata:
        name: {{ include "iagon.fullname" . }}-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.volume.storageClass }}
        storageClassName:  {{ .Values.volume.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.volume.size }}
